# Extracting the movies of 2018

In [1]:
import pandas as pd
import numpy as np

In [2]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2018"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [3]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)
df.head(20)

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,JANUARY,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2]
1,JANUARY,5,The Strange Ones,Vertical Entertainment,Lauren Wolkstein (director); Christopher Radcl...,[3]
2,JANUARY,5,Stratton,Momentum Pictures,"Simon West (director); Duncan Falconer, Warren...",[4]
3,JANUARY,10,Sweet Country,Samuel Goldwyn Films,"Warwick Thornton (director); David Tranter, St...",[5]
4,JANUARY,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[6]
5,JANUARY,12,Proud Mary,Screen Gems,"Babak Najafi (director); John S. Newman, Chris...",[7]
6,JANUARY,12,Acts of Violence,Lionsgate Premiere,Brett Donowho (director); Nicolas Aaron Mezzan...,[8]
7,JANUARY,12,Freak Show,IFC Films,"Trudie Styler (director); Patrick J. Clifton, ...",[9]
8,JANUARY,12,Humor Me,Shout! Factory / Shout! Studios,Sam Hoffman (director/screenplay); Jemaine Cle...,[10]
9,JANUARY,12,Vazante,Music Box Films,Daniela Thomas (director/screenplay); Beto Ama...,[11]
10,JANUARY,18,Mary and the Witch's Flower,GKIDS,Hiromasa Yonebayashi (director/screenplay); Ri...,[12]
11,JANUARY,19,12 Strong,Warner Bros. Pictures / Alcon Entertainment / ...,"Nicolai Fuglsig (director); Peter Craig, Ted T...",[13]
12,JANUARY,19,Den of Thieves,STX Entertainment,Christian Gudegast (director/screenplay); Paul...,[14]
13,JANUARY,19,Forever My Girl,Roadside Attractions,Bethany Ashton Wolf (director/screenplay); Ale...,[15]
14,JANUARY,26,Maze Runner: The Death Cure,20th Century Fox,Wes Ball (director); T.S. Nowlin (screenplay);...,[16]
15,JANUARY,26,The Insult,Cohen Media Group,Ziad Doueiri (director/screenplay); Joelle Tou...,[17]
16,JANUARY,26,Please Stand By,Magnolia Pictures,Ben Lewin (director); Michael Golamco (screenp...,[18]
17,FEBRUARY,2,Winchester,Lionsgate / CBS Films,The Spierig Brothers (director/screenplay); He...,[19]
18,FEBRUARY,2,A Fantastic Woman,Sony Pictures Classics,Sebasti√°n Lelio (director/screenplay); Gonzalo...,[20]
19,FEBRUARY,2,Armed,GVN Releasing,Mario Van Peebles (director/screenplay); Mario...,[21]

In [5]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = '31370eb33aa123089b518141fd2f4347'

In [6]:
from tmdbv3api import Movie
tmdb_movie = Movie()
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    movie_id = result[0].id
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
    data_json = response.json()
    if data_json['genres']:
        genre_str = " " 
        for i in range(0,len(data_json['genres'])):
            genres.append(data_json['genres'][i]['name'])
        return genre_str.join(genres)
    else:
        np.NaN

In [7]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))
df.head(100)

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.,genres
0,JANUARY,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2],Horror Mystery Thriller
1,JANUARY,5,The Strange Ones,Vertical Entertainment,Lauren Wolkstein (director); Christopher Radcl...,[3],Thriller Drama
2,JANUARY,5,Stratton,Momentum Pictures,"Simon West (director); Duncan Falconer, Warren...",[4],Action Thriller
3,JANUARY,10,Sweet Country,Samuel Goldwyn Films,"Warwick Thornton (director); David Tranter, St...",[5],Drama History Western
4,JANUARY,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[6],Action Thriller
...,...,...,...,...,...,...,...
95,MAY,4,Overboard,Metro-Goldwyn-Mayer / Lionsgate / Pantelion Films,"Rob Greenberg, Bob Fisher (directors/screenpla...",[89],Romance Comedy
96,MAY,4,Tully,Focus Features / Bron Studios,Jason Reitman (director); Diablo Cody (screenp...,[95],Drama
97,MAY,4,Bad Samaritan,Electric Entertainment,Dean Devlin (director); Brandon Boyce (screenp...,[96],Thriller Crime Horror
98,MAY,4,The Cleanse,Vertical Entertainment,Bobby Miller (director/screenplay); Johnny Gal...,[97],Drama Comedy Fantasy
99,MAY,4,The Guardians,Music Box Films,Xavier Beauvois (director/screenplay); Nathali...,[98],Family Animation Fantasy Action Adventure

In [8]:
df = df[['Title','Cast and crew','genres']]
df.head()

,Title,Cast and crew,genres
0,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Horror Mystery Thriller
1,The Strange Ones,Lauren Wolkstein (director); Christopher Radcl...,Thriller Drama
2,Stratton,"Simon West (director); Duncan Falconer, Warren...",Action Thriller
3,Sweet Country,"Warwick Thornton (director); David Tranter, St...",Drama History Western
4,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Action Thriller

In [9]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [10]:
df['director_name'] = df['Cast and crew'].map(lambda x: get_director(x))

In [11]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [12]:
df['actor_1_name'] = df['Cast and crew'].map(lambda x: get_actor1(x))

In [13]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [14]:
df['actor_2_name'] = df['Cast and crew'].map(lambda x: get_actor2(x))

In [15]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [16]:
df['actor_3_name'] = df['Cast and crew'].map(lambda x: get_actor3(x))

In [17]:
df = df.rename(columns={'Title':'movie_title'})

In [18]:
new_df = df.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]
new_df.tail(100)

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
169,Peter Berg,Mark Wahlberg,John Malkovich,Lauren Cohan,Action Thriller,Mile 22
170,Bj√∂rn Runge,Glenn Close,Jonathan Pryce,Christian Slater,Drama,The Wife
171,James Cox,Ansel Elgort,Taron Egerton,Kevin Spacey,Drama Thriller,Billionaire Boys Club
172,Jesse Peretz,Ethan Hawke,Rose Byrne,NaN,Comedy Drama Romance,"Juliet, Naked"
173,Rodrigo Cort√©s,AnnaSophia Robb,Uma Thurman,Isabelle Fuhrman,Thriller Drama Fantasy Horror,Down a Dark Hall
...,...,...,...,...,...,...
264,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall,Mystery Adventure Comedy Crime,Holmes & Watson
265,Adam McKay,Christian Bale,Amy Adams,Steve Carell,Thriller Science Fiction Action Adventure,Vice
266,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,Drama History,On the Basis of Sex
267,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell,Thriller Crime Drama Action,Destroyer
268,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry,Science Fiction Mystery Drama Thriller TV Movie,Black Mirror: Bandersnatch

In [19]:
new_df['actor_2_name'] = new_df['actor_2_name'].replace(np.nan, 'unknown')
new_df['actor_3_name'] = new_df['actor_3_name'].replace(np.nan, 'unknown')

In [20]:
new_df['comb'] = new_df['actor_1_name'] + ' ' + new_df['actor_2_name'] + ' '+ new_df['actor_3_name'] + ' '+ new_df['director_name'] +' ' + new_df['genres']
new_df.head()

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Horror Mystery Thriller,Insidious: The Last Key,Lin Shaye Angus Sampson Leigh Whannell Adam Ro...
1,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Thriller Drama,The Strange Ones,Alex Pettyfer James Freedson-Jackson Emily Alt...
2,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Action Thriller,Stratton,Dominic Cooper Austin Stowell Gemma Chan Simon...
3,Warwick Thornton,Bryan Brown,Sam Neill,unknown,Drama History Western,Sweet Country,Bryan Brown Sam Neill unknown Warwick Thornton...
4,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Action Thriller,The Commuter,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...

## Extracting the movies of 2019

In [21]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2019"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [22]:
df_19 = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)
df_19.head()

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,JANUARY,4,Escape Room,Columbia Pictures,"Adam Robitel (director); Bragi F. Schut, Maria...",[2]
1,JANUARY,4,Rust Creek,IFC Films,Jen McGowan (director); Julie Lipson (screenpl...,[3]
2,JANUARY,4,American Hangman,Hangman Justice Productions,Wilson Coneybeare (director/screenplay); Donal...,[4]
3,JANUARY,11,A Dog's Way Home,Columbia Pictures,Charles Martin Smith (director); W. Bruce Came...,[5]
4,JANUARY,11,The Upside,STX Entertainment,Neil Burger (director); Jon Hartmere (screenpl...,[6]

In [23]:
df_19['genres'] = df_19['Title'].map(lambda x: get_genre(str(x)))

In [24]:
df_new = df_19[['Title','Cast and crew','genres']]

In [25]:
df_new.tail()

,Title,Cast and crew,genres
237,Spies in Disguise,"Nick Bruno, Troy Quane (directors); Brad Copel...",Animation Action Adventure Comedy Family
238,Little Women,Greta Gerwig (director/screenplay); Saoirse Ro...,Drama Romance
239,1917,Sam Mendes (director/screenplay); Krysty Wilso...,War Drama Action Thriller
240,Just Mercy,"Destin Daniel Cretton (director/screenplay), A...",Drama Crime History
241,Clemency,Chinonye Chukwu (director/screenplay); Alfre W...,Drama

In [26]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [27]:
df_new['director_name'] = df_new['Cast and crew'].map(lambda x: get_director(str(x)))

<ipython-input-27-c8b7e673957b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['director_name'] = df_new['Cast and crew'].map(lambda x: get_director(str(x)))

In [28]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [29]:
df_new['actor_1_name'] = df_new['Cast and crew'].map(lambda x: get_actor1(x))

<ipython-input-29-000904f88d38>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['actor_1_name'] = df_new['Cast and crew'].map(lambda x: get_actor1(x))

In [30]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [31]:
df_new['actor_2_name'] = df_new['Cast and crew'].map(lambda x: get_actor2(x))

<ipython-input-31-405f5a45bc4c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['actor_2_name'] = df_new['Cast and crew'].map(lambda x: get_actor2(x))

In [32]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [33]:
df_new['actor_3_name'] = df_new['Cast and crew'].map(lambda x: get_actor3(x))

In [34]:
df_new = df_new.rename(columns={'Title':'movie_title'})

In [35]:
df_new = df_new.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]
df_new.tail(100)

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
142,Johannes Roberts,John Corbett,Nia Long,Sophie Nelisse,Horror,47 Meters Down: Uncaged
143,William McGregor,Maxine Peake,Eleanor Worthington Cox,Richard Harrington,Drama Mystery Horror History,Gwen
144,"Matt Bettinelli-Olpin, Tyler Gillett",Samara Weaving,Adam Brody,Mark O'Brien,Horror Thriller Comedy,Ready or Not
145,Ric Roman Waugh,Gerard Butler,Morgan Freeman,Jada Pinkett Smith,Action Thriller,Angel Has Fallen
146,Paul Downs Colaizzo,Jillian Bell,Michaela Watkins,Utkarsh Ambudkar,Comedy Drama,Brittany Runs a Marathon
...,...,...,...,...,...,...
237,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Animation Action Adventure Comedy Family,Spies in Disguise
238,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance,Little Women
239,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,War Drama Action Thriller,1917
240,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama Crime History,Just Mercy
241,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,Clemency

In [36]:
df_new['movie_title'] = df_new['movie_title'].str.lower()

In [37]:
df_new['comb'] = df_new['actor_1_name'] + ' ' + df_new['actor_2_name'] + ' '+ df_new['actor_3_name'] + ' '+ df_new['director_name'] +' ' + df_new['genres']

In [38]:
df_new.head()

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Taylor Russell,Logan Miller,Deborah Ann Woll,Thriller Action Mystery Adventure Horror,escape room,Taylor Russell Logan Miller Deborah Ann Woll A...
1,Jen McGowan,Hermione Corfield,Jay Paulson,Sean O'Bryan,Thriller Drama,rust creek,Hermione Corfield Jay Paulson Sean O'Bryan Jen...
2,Wilson Coneybeare,Donald Sutherland,Vincent Kartheiser,Oliver Dennis,Thriller,american hangman,Donald Sutherland Vincent Kartheiser Oliver De...
3,Charles Martin Smith,Bryce Dallas Howard,Edward James Olmos,Alexandra Shipp,Drama Adventure Family,a dog's way home,Bryce Dallas Howard Edward James Olmos Alexand...
4,Neil Burger,Bryan Cranston,Kevin Hart,Nicole Kidman,Comedy Drama,the upside,Bryan Cranston Kevin Hart Nicole Kidman Neil B...

In [39]:
mod_df = new_df.append(df_new,ignore_index=True)
mod_df.head()

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Horror Mystery Thriller,Insidious: The Last Key,Lin Shaye Angus Sampson Leigh Whannell Adam Ro...
1,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Thriller Drama,The Strange Ones,Alex Pettyfer James Freedson-Jackson Emily Alt...
2,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Action Thriller,Stratton,Dominic Cooper Austin Stowell Gemma Chan Simon...
3,Warwick Thornton,Bryan Brown,Sam Neill,unknown,Drama History Western,Sweet Country,Bryan Brown Sam Neill unknown Warwick Thornton...
4,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Action Thriller,The Commuter,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...

In [40]:
old_df = pd.read_csv('C:/Users/SANTHOSH/Desktop/practise/flask/movie_recommandation/datasets/new_data.csv')
old_df.tail(100)

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
5264,Alberto G. Rodriguez,Eric Roberts,Leila Almas,Jaime Zevallos,Thriller Drama Mystery,the summoning,Eric Roberts Leila Almas Jaime Zevallos Albert...
5265,Mark Cullen,Bruce Willis,Jason Momoa,John Goodman,Action Comedy Thriller,once upon a time in venice,Bruce Willis Jason Momoa John Goodman Mark Cul...
5266,Carlo Guillermo Proto,Denis Harting,Peggy Roux,Lauviah Harting,Documentary,resurrecting hassan,Denis Harting Peggy Roux Lauviah Harting Carlo...
5267,Bonni Cohen Jon Shenk,Al Gore,Barack Obama,Donald Trump,Documentary,an inconvenient sequel: truth to power,Al Gore Barack Obama Donald Trump Bonni Cohen ...
5268,Neill Blomkamp,Sigourney Weaver,Eugene Khumbanyiwa,Robert Hobbs,Action Sci-Fi,rakka,Sigourney Weaver Eugene Khumbanyiwa Robert Hob...
...,...,...,...,...,...,...,...
5359,Jim Strouse,Jessica Williams,Chris O'Dowd,Keith Stanfield,Romance Comedy,the incredible jessica james,Jessica Williams Chris O'Dowd Keith Stanfield ...
5360,Farhad Mann,Adelaide Kane,Benjamin Hollingsworth,Jean Louisa Kelly,Romance,can't buy my love,Adelaide Kane Benjamin Hollingsworth Jean Loui...
5361,Hannaleena Hauru,Inka Haapam√§ki,Rosa Honkonen,Tiitus Rantala,Romance Comedy,thick lashes of lauri m√§ntyvaara,Inka Haapam√§ki Rosa Honkonen Tiitus Rantala Ha...
5362,Jonathan A. Rosenbaum,Lou Diamond Phillips,Wallace Shawn,Gina Holden,Crime Comedy Action Family,cop and a half: new recruit,Lou Diamond Phillips Wallace Shawn Gina Holden...
5363,Ravi Udyawar,Sridevi Kapoor,Sajal Ali,Akshaye Khanna,Crime Drama Thriller,mom,Sridevi Kapoor Sajal Ali Akshaye Khanna Ravi U...

In [41]:
final_df = old_df.append(mod_df,ignore_index=True)
final_df.head(200)

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens¬† ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
195,Tony Gilroy,Jeremy Renner,Scott Glenn,Stacy Keach,Action Adventure Thriller,the bourne legacy,Jeremy Renner Scott Glenn Stacy Keach Tony Gil...
196,Joel Schumacher,Michael Gough,Vivica A. Fox,John Glover,Action,batman & robin,Michael Gough Vivica A. Fox John Glover Joel S...
197,Ron Howard,Clint Howard,T.J. Thyne,Molly Shannon,Comedy Family Fantasy,how the grinch stole christmas,Clint Howard T.J. Thyne Molly Shannon Ron Howa...
198,Roland Emmerich,Jake Gyllenhaal,Dennis Quaid,Sela Ward,Action Adventure Sci-Fi Thriller,the day after tomorrow,Jake Gyllenhaal Dennis Quaid Sela Ward Roland ...
199,John Woo,Tom Cruise,Dougray Scott,Richard Roxburgh,Action Adventure Thriller,mission: impossible ii,Tom Cruise Dougray Scott Richard Roxburgh John...

In [42]:
final_df.isna().sum()

director_name     0
actor_1_name      0
actor_2_name      1
actor_3_name     15
genres            3
movie_title       0
comb             18
dtype: int64

In [43]:
final_df = final_df.dropna(how='any')

In [44]:
final_df.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [45]:
final_df.to_csv('C:/Users/SANTHOSH/Desktop/practise/flask/movie_recommandation/datasets/final_data.csv',index=False)